[package]
name = "cli"
edition = "2021"
version = "0.4.0"

[dependencies]
glob = "0.3.0"
gray_matter = "0.2.4"
serde_json = "1"

[dependencies.clap]
version = "4.0.19"
features = ["derive"]

[dependencies.serde]
version = "1"
features = ["derive"]
