[package]
name = "cli"
version = "0.2.6"
edition = "2021"

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
glob = "0.3.0"
gray_matter = "0.2.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
