[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.1"
scheduling-api = { path = "../../../calendar-scheduler/crates/scheduling-api" }
caldav-utils = { path = "../../../calendar-scheduler/crates/caldav-utils" }
# clap = { version = "4.0.19", features = ["derive"] }
# reqwest = { version = "0.11.12", features = ["rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.3.0", features = ["fs"] }
